### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by gbastien** [collective/ArchGenXML#5]
Hi @tdesvenain @vincentfretin 

we still use this to generate WFs and we have some useful changes that are not in release 2.6, could you please give me pypi rights to release 2.7 or do it?

Thank you!

Gauthier

**Comment by vincentfretin** [comment]
You are owner now.

**Comment by gbastien** [comment]
Thank you, I do this tomorrow.

Gauthier

**Comment by gbastien** [comment]
Released : https://pypi.python.org/pypi/archgenxml
